global:
    use_gpu: True
    verbose: True
    print_shape: False
    activate_timer: False
    shuffle_dataloader: True
    dataloader_drop_last: True
    exp_name: 'protein_test'

optimizer:
    optimizer_type: 'adam'
    b1: 0.5
    b2: 0.999
    lr: 1e-3

sdf_network:
    d_out: 1
    d_in: 3
    d_hidden: 256
    n_layers: 8
    skip_in: [4]
    multires: 0
    bias: 0.5
    scale: 1.0
    geometric_init: True
    weight_norm: True

trainer:
    trainer_mode: 'train'
    log_dir: '/scratch/projects/vision/data/533/output/'

    warm_up_end: 1000

    num_epochs: 100
    batch_size: 5000

    save_every: 50
    valid_every: 50
    log_cli_every: 50

validate:
    validate_num_batches: 10

dataset:
    dataset_num_workers: 0

    data_path: '/scratch/projects/vision/data/533'
    dataset_name: 'protein_test'
