global:
    log_time: False
    use_gpu: True
    verbose: True
    print_shape: False
    shuffle_dataloader: True
    dataloader_drop_last: True
    exp_name: 'ssl_redshift'

optimizer:
    optimizer_type: 'adamw'
    lr: 0.0005
    min_lr: 1e-06

network:
    arch: vit_tiny
    patch_size: 16
    out_dim: 65536
    num_specz_bins: 180
    norm_last_layer: True
    use_bn_in_head: False
    in_chans: 5

    momentum_teacher: 0.996
    teacher_temp: 0.04
    warmup_teacher_temp: 0.04
    warmup_teacher_temp_epochs: 0

trainer:
    trainer_mode: 'redshift_train'
    log_dir: '/scratch/projects/vision/data/pdr3/output/'
    gpu_data: ["crops","specz_bin"]

    num_epochs: 2000
    warmup_epochs: 500
    pretrain_batch_size: 500 # transform takes 0.6s
    batch_size_per_gpu: 64

    save_every: 400
    valid_every: 10
    log_cli_every: 10

    clip_grad: 3.0
    use_fp16: True
    weight_decay: 0.04
    weight_decay_end: 0.4
    freeze_last_layer: 1
    drop_path_rate: 0.1

    resume_train: False
    #resume_log_dir: '20230404-123911_no_spatial_decode'
    #resume_model_name: 'model-ep2000-it0.pth'
    pretrained_log_dir: '20230416-180501-pre_training'
    pretrained_model_fname: 'model-ep100-it129.pth'

validate:
    #validate_num_batches: 10
    best_model_fname: "best_model.pth"
    best_model_log_dir: '20230414-104714-redshift_train'
    catastrophic_outlier_thresh: 0.05

dataset:
    load_data_from_cache: True
    dataset_num_workers: 5
    num_patches_per_group: 2
    crop_sz: 96
    split_ratio: [0.7,0.2,0.1]
    plot_crops: False
    num_crops_to_plot: 10
    specz_upper_lim: 7 # test1
    split_table: False

    dino_global_crop_dim: 84
    dino_local_crop_dim: 64
    dino_num_local_crops: 4
    dino_rotate_mode: "wrap"
    dino_jitter_lim: 10

    data_path: '/scratch/projects/vision/data/pdr3'
    redshift_path: "redshift/test1"

    source_table_fname: "detections_redshifts_pdf3.fits"
    train_specz_table_fname: "train_specz.fits"
    valid_specz_table_fname: "valid_specz.fits"
    test_specz_table_fname: "test_specz.fits"

    sensor_collection_name: '5_grizy'
    bands: ["G","R","I","Z","Y"]

    global_crops_scale: [0.4, 1.0]
    local_crops_number: 8
    local_crops_scale: [0.05, 0.4]